name: CI/CD Pipeline - Cidades Inteligentes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciando Compilação
        run: echo "Iniciando a compilação do projeto"
      
      - name: Instalar Dependências
        run: echo "Instalando as dependências"
      
      - name: Compilar o Projeto
        run: echo "Compilando o projeto" 

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para Staging
        run: echo "Deploy para o ambiente de Staging"

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Deploy para Produção
        run: echo "Deploy para o ambiente de Produção"
